meta:
  business:
    phone-number-id: YOUR_PHONE_NUMBER_ID
    access-token: YOUR_ACCESS_TOKEN

twilio:
  account-sid: YOUR_ACCOUNT_SID
  auth-token: YOUR_AUTH_TOKEN
  from-number: YOUR_TWILIO_WHATSAPP_OR_SMS_NUMBER

gupshup:
  api-key: YOUR_GUPSHUP_API_KEY
  base-url: https://api.gupshup.io/sm/api/v1

zoho:
  api-base-url: https://www.zohoapis.com/crm/v2
  auth-base-url: https://accounts.zoho.com/oauth/v2
  client-id: YOUR_CLIENT_ID
  client-secret: YOUR_CLIENT_SECRET
  refresh-token: YOUR_REFRESH_TOKEN

spring:
  main:
    allow-bean-definition-overriding: true

  # ─── Database / JPA Configuration ────────────────────────────────────────
  datasource:
    url: jdbc:postgresql://localhost:5432/your_db
    username: your_user
    password: your_pass

  jpa:
    hibernate:
      ddl-auto: update # auto-create/update tables
    show-sql: true # log SQL statements

logging:
  pattern:
    console: >-
      %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %X{notificationId} - %msg%n
